services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HOST: "${HOST}"
      PORT: "${PORT}"
      APP_MODE: "${APP_MODE}"
      SIMPLE_SERVICE_URL: "${SIMPLE_SERVICE_URL}"
      COMPLEX_SERVICE_URL: "${COMPLEX_SERVICE_URL}"
    ports:
      - "${PORT}:${PORT}"
    restart: on-failure
