// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: protos/service-simple.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstNumber   int32                  `protobuf:"zigzag32,1,opt,name=first_number,json=firstNumber,proto3" json:"first_number,omitempty"`
	SecondNumber  int32                  `protobuf:"zigzag32,2,opt,name=second_number,json=secondNumber,proto3" json:"second_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRequest) Reset() {
	*x = OperationRequest{}
	mi := &file_protos_service_simple_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRequest) ProtoMessage() {}

func (x *OperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_simple_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRequest.ProtoReflect.Descriptor instead.
func (*OperationRequest) Descriptor() ([]byte, []int) {
	return file_protos_service_simple_proto_rawDescGZIP(), []int{0}
}

func (x *OperationRequest) GetFirstNumber() int32 {
	if x != nil {
		return x.FirstNumber
	}
	return 0
}

func (x *OperationRequest) GetSecondNumber() int32 {
	if x != nil {
		return x.SecondNumber
	}
	return 0
}

type OperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"zigzag32,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_protos_service_simple_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_simple_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_protos_service_simple_proto_rawDescGZIP(), []int{1}
}

func (x *OperationResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_protos_service_simple_proto protoreflect.FileDescriptor

const file_protos_service_simple_proto_rawDesc = "" +
	"\n" +
	"\x1bprotos/service-simple.proto\"Z\n" +
	"\x10OperationRequest\x12!\n" +
	"\ffirst_number\x18\x01 \x01(\x11R\vfirstNumber\x12#\n" +
	"\rsecond_number\x18\x02 \x01(\x11R\fsecondNumber\"+\n" +
	"\x11OperationResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x11R\x06result2\xcf\x01\n" +
	"\rSimpleCompute\x12.\n" +
	"\x03Add\x12\x11.OperationRequest\x1a\x12.OperationResponse\"\x00\x12.\n" +
	"\x03Sub\x12\x11.OperationRequest\x1a\x12.OperationResponse\"\x00\x12.\n" +
	"\x03Mul\x12\x11.OperationRequest\x1a\x12.OperationResponse\"\x00\x12.\n" +
	"\x03Div\x12\x11.OperationRequest\x1a\x12.OperationResponse\"\x00B9Z7github.com/lubie-koty/rpc-compute-service-simple/protosb\x06proto3"

var (
	file_protos_service_simple_proto_rawDescOnce sync.Once
	file_protos_service_simple_proto_rawDescData []byte
)

func file_protos_service_simple_proto_rawDescGZIP() []byte {
	file_protos_service_simple_proto_rawDescOnce.Do(func() {
		file_protos_service_simple_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_service_simple_proto_rawDesc), len(file_protos_service_simple_proto_rawDesc)))
	})
	return file_protos_service_simple_proto_rawDescData
}

var file_protos_service_simple_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_service_simple_proto_goTypes = []any{
	(*OperationRequest)(nil),  // 0: OperationRequest
	(*OperationResponse)(nil), // 1: OperationResponse
}
var file_protos_service_simple_proto_depIdxs = []int32{
	0, // 0: SimpleCompute.Add:input_type -> OperationRequest
	0, // 1: SimpleCompute.Sub:input_type -> OperationRequest
	0, // 2: SimpleCompute.Mul:input_type -> OperationRequest
	0, // 3: SimpleCompute.Div:input_type -> OperationRequest
	1, // 4: SimpleCompute.Add:output_type -> OperationResponse
	1, // 5: SimpleCompute.Sub:output_type -> OperationResponse
	1, // 6: SimpleCompute.Mul:output_type -> OperationResponse
	1, // 7: SimpleCompute.Div:output_type -> OperationResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_service_simple_proto_init() }
func file_protos_service_simple_proto_init() {
	if File_protos_service_simple_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_service_simple_proto_rawDesc), len(file_protos_service_simple_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_service_simple_proto_goTypes,
		DependencyIndexes: file_protos_service_simple_proto_depIdxs,
		MessageInfos:      file_protos_service_simple_proto_msgTypes,
	}.Build()
	File_protos_service_simple_proto = out.File
	file_protos_service_simple_proto_goTypes = nil
	file_protos_service_simple_proto_depIdxs = nil
}
