// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.1
// source: protos/service-simple.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SimpleCompute_Add_FullMethodName = "/SimpleCompute/Add"
	SimpleCompute_Sub_FullMethodName = "/SimpleCompute/Sub"
	SimpleCompute_Mul_FullMethodName = "/SimpleCompute/Mul"
	SimpleCompute_Div_FullMethodName = "/SimpleCompute/Div"
)

// SimpleComputeClient is the client API for SimpleCompute service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimpleComputeClient interface {
	Add(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	Sub(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	Mul(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	Div(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error)
}

type simpleComputeClient struct {
	cc grpc.ClientConnInterface
}

func NewSimpleComputeClient(cc grpc.ClientConnInterface) SimpleComputeClient {
	return &simpleComputeClient{cc}
}

func (c *simpleComputeClient) Add(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, SimpleCompute_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simpleComputeClient) Sub(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, SimpleCompute_Sub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simpleComputeClient) Mul(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, SimpleCompute_Mul_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simpleComputeClient) Div(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, SimpleCompute_Div_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimpleComputeServer is the server API for SimpleCompute service.
// All implementations must embed UnimplementedSimpleComputeServer
// for forward compatibility.
type SimpleComputeServer interface {
	Add(context.Context, *OperationRequest) (*OperationResponse, error)
	Sub(context.Context, *OperationRequest) (*OperationResponse, error)
	Mul(context.Context, *OperationRequest) (*OperationResponse, error)
	Div(context.Context, *OperationRequest) (*OperationResponse, error)
	mustEmbedUnimplementedSimpleComputeServer()
}

// UnimplementedSimpleComputeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSimpleComputeServer struct{}

func (UnimplementedSimpleComputeServer) Add(context.Context, *OperationRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedSimpleComputeServer) Sub(context.Context, *OperationRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sub not implemented")
}
func (UnimplementedSimpleComputeServer) Mul(context.Context, *OperationRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mul not implemented")
}
func (UnimplementedSimpleComputeServer) Div(context.Context, *OperationRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Div not implemented")
}
func (UnimplementedSimpleComputeServer) mustEmbedUnimplementedSimpleComputeServer() {}
func (UnimplementedSimpleComputeServer) testEmbeddedByValue()                       {}

// UnsafeSimpleComputeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimpleComputeServer will
// result in compilation errors.
type UnsafeSimpleComputeServer interface {
	mustEmbedUnimplementedSimpleComputeServer()
}

func RegisterSimpleComputeServer(s grpc.ServiceRegistrar, srv SimpleComputeServer) {
	// If the following call pancis, it indicates UnimplementedSimpleComputeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SimpleCompute_ServiceDesc, srv)
}

func _SimpleCompute_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleComputeServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimpleCompute_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleComputeServer).Add(ctx, req.(*OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimpleCompute_Sub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleComputeServer).Sub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimpleCompute_Sub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleComputeServer).Sub(ctx, req.(*OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimpleCompute_Mul_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleComputeServer).Mul(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimpleCompute_Mul_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleComputeServer).Mul(ctx, req.(*OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimpleCompute_Div_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleComputeServer).Div(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimpleCompute_Div_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleComputeServer).Div(ctx, req.(*OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SimpleCompute_ServiceDesc is the grpc.ServiceDesc for SimpleCompute service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimpleCompute_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SimpleCompute",
	HandlerType: (*SimpleComputeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _SimpleCompute_Add_Handler,
		},
		{
			MethodName: "Sub",
			Handler:    _SimpleCompute_Sub_Handler,
		},
		{
			MethodName: "Mul",
			Handler:    _SimpleCompute_Mul_Handler,
		},
		{
			MethodName: "Div",
			Handler:    _SimpleCompute_Div_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/service-simple.proto",
}
